import PptxGenJS from 'pptxgenjs';
import type { ExportFrame } from './exportTypes';
import { formatTimestamp } from './exportTypes';
import { loadImage } from './exportUtils';

export interface PptxExportOptions {
  title: string;
  author?: string;
  fps?: number;
  layout?: '1x1' | '2x2' | '3x3';
  includeTimestamp?: boolean;
  includeNote?: boolean;
  theme?: 'dark' | 'light';
}

const LAYOUTS = {
  '1x1': { cols: 1, rows: 1, framesPerSlide: 1 },
  '2x2': { cols: 2, rows: 2, framesPerSlide: 4 },
  '3x3': { cols: 3, rows: 3, framesPerSlide: 9 },
};

export async function exportToPptxWithJsPptx(
  frames: ExportFrame[],
  filename: string,
  options: PptxExportOptions
): Promise<void> {
  const {
    title,
    author = 'Storyboard Copilot',
    fps = 24,
    layout = '2x2',
    includeTimestamp = true,
    includeNote = true,
    theme = 'dark',
  } = options;

  const layoutConfig = LAYOUTS[layout];
  const totalSlides = Math.ceil(frames.length / layoutConfig.framesPerSlide);

  const pptx = new PptxGenJS();
  pptx.author = author;
  pptx.title = title;
  pptx.subject = 'Storyboard Export';

  const bgColor = theme === 'dark' ? '1a1a1a' : 'ffffff';
  const textColor = theme === 'dark' ? 'ffffff' : '333333';
  const mutedColor = theme === 'dark' ? '999999' : '666666';
  const frameBgColor = theme === 'dark' ? '2d2d2d' : 'f0f0f0';

  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: bgColor };

  titleSlide.addText(title, {
    x: 0.5,
    y: 2.5,
    w: 9,
    h: 1,
    fontSize: 36,
    bold: true,
    color: textColor,
    align: 'center',
  });

  titleSlide.addText(`Generated by Storyboard Copilot`, {
    x: 0.5,
    y: 3.8,
    w: 9,
    h: 0.5,
    fontSize: 14,
    color: mutedColor,
    align: 'center',
  });

  titleSlide.addText(`${frames.length} frames | ${totalSlides} slides`, {
    x: 0.5,
    y: 4.4,
    w: 9,
    h: 0.5,
    fontSize: 12,
    color: mutedColor,
    align: 'center',
  });

  for (let slideIndex = 0; slideIndex < totalSlides; slideIndex++) {
    const slide = pptx.addSlide();
    slide.background = { color: bgColor };

    const slideTitle = `${title} - Page ${slideIndex + 1}/${totalSlides}`;
    slide.addText(slideTitle, {
      x: 0.5,
      y: 0.2,
      w: 9,
      h: 0.4,
      fontSize: 14,
      bold: true,
      color: textColor,
    });

    const margin = 0.4;
    const headerHeight = 0.7;
    const footerHeight = 0.4;
    const gap = 0.15;

    const usableWidth = 10 - margin * 2;
    const usableHeight = 7.5 - margin * 2 - headerHeight - footerHeight;

    const cellWidth = (usableWidth - gap * (layoutConfig.cols - 1)) / layoutConfig.cols;
    const cellHeight = (usableHeight - gap * (layoutConfig.rows - 1)) / layoutConfig.rows;

    const pageFrames = frames.slice(
      slideIndex * layoutConfig.framesPerSlide,
      (slideIndex + 1) * layoutConfig.framesPerSlide
    );

    for (let i = 0; i < pageFrames.length; i++) {
      const frame = pageFrames[i];
      const col = i % layoutConfig.cols;
      const row = Math.floor(i / layoutConfig.cols);

      const x = margin + col * (cellWidth + gap);
      const y = margin + headerHeight + row * (cellHeight + gap);

      slide.addShape(pptx.ShapeType.rect, {
        x,
        y,
        w: cellWidth,
        h: cellHeight,
        fill: { color: frameBgColor },
        line: { color: theme === 'dark' ? '3d3d3d' : 'd0d0d0', width: 0.5 },
      });

      if (frame.imageUrl) {
        try {
          const img = await loadImage(frame.imageUrl);
          const canvas = document.createElement('canvas');
          canvas.width = img.width;
          canvas.height = img.height;
          const ctx = canvas.getContext('2d');
          if (ctx) {
            ctx.drawImage(img, 0, 0);
            const imgData = canvas.toDataURL('image/jpeg', 0.85);

            const imgAspectRatio = img.height / img.width;
            const cellAspectRatio = cellHeight / cellWidth;

            let drawWidth: number;
            let drawHeight: number;
            let drawX: number;
            let drawY: number;

            if (imgAspectRatio > cellAspectRatio) {
              drawHeight = cellHeight - 0.2;
              drawWidth = (cellHeight - 0.2) / imgAspectRatio;
              drawX = x + (cellWidth - drawWidth) / 2;
              drawY = y + 0.1;
            } else {
              drawWidth = cellWidth - 0.2;
              drawHeight = (cellWidth - 0.2) * imgAspectRatio;
              drawX = x + 0.1;
              drawY = y + (cellHeight - drawHeight) / 2;
            }

            slide.addImage({
              data: imgData,
              x: drawX,
              y: drawY,
              w: drawWidth,
              h: drawHeight,
            });
          }
        } catch {
          slide.addText('Image unavailable', {
            x,
            y: y + cellHeight / 2 - 0.2,
            w: cellWidth,
            h: 0.4,
            fontSize: 8,
            color: mutedColor,
            align: 'center',
          });
        }
      }

      const labelY = y + cellHeight - 0.35;
      slide.addText(`#${slideIndex * layoutConfig.framesPerSlide + i + 1}`, {
        x: x + 0.08,
        y: labelY,
        w: 0.5,
        h: 0.25,
        fontSize: 8,
        bold: true,
        color: textColor,
      });

      if (includeTimestamp && frame.timestamp) {
        slide.addText(formatTimestamp(frame.index, fps), {
          x: x + cellWidth - 0.6,
          y: labelY,
          w: 0.55,
          h: 0.25,
          fontSize: 7,
          color: mutedColor,
          align: 'right',
        });
      }

      if (includeNote && frame.note) {
        const noteLines = wrapText(frame.note, Math.floor(cellWidth * 6), 2);
        noteLines.forEach((line, idx) => {
          slide.addText(line, {
            x: x + 0.08,
            y: y + 0.08 + idx * 0.2,
            w: cellWidth - 0.16,
            h: 0.2,
            fontSize: 6,
            color: mutedColor,
            valign: 'top',
          });
        });
      }
    }

    slide.addText('Generated by Storyboard Copilot', {
      x: 0.5,
      y: 7.2,
      w: 9,
      h: 0.3,
      fontSize: 8,
      color: mutedColor,
      align: 'center',
    });
  }

  await pptx.writeFile({ fileName: `${filename}.pptx` });
}

function wrapText(text: string, maxCharsPerLine: number, maxLines?: number): string[] {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let currentLine = '';

  for (const word of words) {
    if ((currentLine + ' ' + word).trim().length <= maxCharsPerLine) {
      currentLine = (currentLine + ' ' + word).trim();
    } else {
      if (currentLine) lines.push(currentLine);
      currentLine = word;
      if (maxLines && lines.length >= maxLines) break;
    }
  }

  if (currentLine && (!maxLines || lines.length < maxLines)) {
    lines.push(currentLine);
  }

  return lines;
}

export async function exportStoryboardToPptx(
  frames: ExportFrame[],
  filename: string,
  options: {
    title?: string;
    rows?: number;
    cols?: number;
    includeNotes?: boolean;
    theme?: 'dark' | 'light';
  } = {}
): Promise<void> {
  const {
    title = 'Storyboard',
    rows = 2,
    cols = 2,
    includeNotes = true,
    theme = 'dark',
  } = options;

  const framesPerSlide = rows * cols;
  const totalSlides = Math.ceil(frames.length / framesPerSlide);

  const pptx = new PptxGenJS();
  pptx.author = 'Storyboard Copilot';
  pptx.title = title;
  pptx.subject = 'Storyboard Export';

  const bgColor = theme === 'dark' ? '1a1a1a' : 'ffffff';
  const textColor = theme === 'dark' ? 'ffffff' : '333333';
  const mutedColor = theme === 'dark' ? '999999' : '666666';

  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: bgColor };

  titleSlide.addText(title, {
    x: 0.5,
    y: 2.5,
    w: 9,
    h: 1,
    fontSize: 36,
    bold: true,
    color: textColor,
    align: 'center',
  });

  titleSlide.addText(`Generated by Storyboard Copilot`, {
    x: 0.5,
    y: 3.8,
    w: 9,
    h: 0.5,
    fontSize: 14,
    color: mutedColor,
    align: 'center',
  });

  const margin = 0.4;
  const headerHeight = 0.8;
  const footerHeight = 0.4;
  const gap = 0.2;

  const usableWidth = 10 - margin * 2;
  const usableHeight = 7.5 - margin * 2 - headerHeight - footerHeight;

  const cellWidth = (usableWidth - gap * (cols - 1)) / cols;
  const cellHeight = (usableHeight - gap * (rows - 1)) / rows;

  for (let slideIndex = 0; slideIndex < totalSlides; slideIndex++) {
    const slide = pptx.addSlide();
    slide.background = { color: bgColor };

    slide.addText(title, {
      x: margin,
      y: 0.25,
      w: usableWidth,
      h: 0.4,
      fontSize: 18,
      bold: true,
      color: textColor,
    });

    const pageFrames = frames.slice(
      slideIndex * framesPerSlide,
      (slideIndex + 1) * framesPerSlide
    );

    for (let i = 0; i < pageFrames.length; i++) {
      const frame = pageFrames[i];
      const col = i % cols;
      const row = Math.floor(i / cols);

      const x = margin + col * (cellWidth + gap);
      const y = margin + headerHeight + row * (cellHeight + gap);

      slide.addShape(pptx.ShapeType.rect, {
        x,
        y,
        w: cellWidth,
        h: cellHeight,
        fill: { color: theme === 'dark' ? '2d2d2d' : 'f5f5f5' },
        line: { color: theme === 'dark' ? '3d3d3d' : 'e0e0e0', width: 0.5 },
      });

      if (frame.imageUrl) {
        try {
          const img = await loadImage(frame.imageUrl);
          const canvas = document.createElement('canvas');
          canvas.width = img.width;
          canvas.height = img.height;
          const ctx = canvas.getContext('2d');
          if (ctx) {
            ctx.drawImage(img, 0, 0);
            const imgData = canvas.toDataURL('image/jpeg', 0.9);

            const imgRatio = img.height / img.width;
            const cellRatio = cellHeight / cellWidth;

            let dw: number;
            let dh: number;
            let dx: number;
            let dy: number;

            if (imgRatio > cellRatio) {
              dh = cellHeight - 0.2;
              dw = (cellHeight - 0.2) / imgRatio;
              dx = x + (cellWidth - dw) / 2;
              dy = y + 0.1;
            } else {
              dw = cellWidth - 0.2;
              dh = (cellWidth - 0.2) * imgRatio;
              dx = x + 0.1;
              dy = y + (cellHeight - dh) / 2;
            }

            slide.addImage({
              data: imgData,
              x: dx,
              y: dy,
              w: dw,
              h: dh,
            });
          }
        } catch {
          slide.addText('No preview', {
            x: x + cellWidth / 2 - 0.5,
            y: y + cellHeight / 2 - 0.15,
            w: 1,
            h: 0.3,
            fontSize: 8,
            color: mutedColor,
            align: 'center',
          });
        }
      }

      slide.addText(`#${slideIndex * framesPerSlide + i + 1}`, {
        x: x + 0.08,
        y: y + cellHeight - 0.35,
        w: 0.5,
        h: 0.25,
        fontSize: 9,
        bold: true,
        color: textColor,
      });

      if (includeNotes && frame.note) {
        const noteLines = wrapText(frame.note, Math.floor(cellWidth * 6), 2);
        noteLines.forEach((line, idx) => {
          slide.addText(line, {
            x: x + 0.08,
            y: y + 0.08 + idx * 0.2,
            w: cellWidth - 0.16,
            h: 0.2,
            fontSize: 6,
            color: mutedColor,
            valign: 'top',
          });
        });
      }
    }

    slide.addText(`Page ${slideIndex + 1} of ${totalSlides}`, {
      x: margin,
      y: 7.2,
      w: usableWidth,
      h: 0.3,
      fontSize: 9,
      color: mutedColor,
      align: 'center',
    });
  }

  await pptx.writeFile({ fileName: `${filename}.pptx` });
}
